repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
---
releases:
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.11.0

  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.15.3

helmDefaults:
  kubeconfig: /etc/rancher/k3s/k3s.yaml
