---
instance:
  distribution:
    version:
  sync:
    kind: GitRepository
    url: ssh://forgejo@git.dev.002042.xyz/websheriff/nixcfg.git
    ref: refs/heads/main
    patch: kubernetes/flux
    interval: 2m
    pullSecret:
